# Copyright (c) Facebook, Inc. and its affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

version: '3'
volumes:
  whatsappMedia:
    driver: local
services:
  wacore:
    image: docker.whatsapp.biz/coreapp:<WA_API_VERSION>
    command: ["/opt/whatsapp/bin/launch_within_docker.sh"]
    volumes:
     - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WA_RUNNING_ENV_VERSION: v2.2.3
      ORCHESTRATION: DOCKER-COMPOSE
    network_mode: bridge
    deploy:
      restart_policy:
        condition: any
  waweb:
    image: docker.whatsapp.biz/web:<WA_API_VERSION>
    command: ["/opt/whatsapp/bin/launch_within_docker.sh"]
    volumes:
      - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WACORE_HOSTNAME: wacore
      WA_RUNNING_ENV_VERSION: v2.2.3
      ORCHESTRATION: DOCKER-COMPOSE
    ports:
      - "443:443"
    depends_on:
      - "wacore"
    links:
      - wacore
    network_mode: bridge
    deploy:
      restart_policy:
        condition: any
  proxy:
    image: diouxx/apache-proxy
    ports:
     - "80:80"
    depends_on:
     - "waweb"
    volumes:
      - ./proxy_config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    links:
     - waweb
    network_mode: bridge
    deploy:
      restart_policy:
        condition: any
